tunnel: e6d339d0-23b9-49ab-8e56-ec92cb5bd817
credentials-file: C:\Users\flore\.cloudflared\e6d339d0-23b9-49ab-8e56-ec92cb5bd817.json

ingress:
  - hostname: filsha.org
    service: http://localhost:5000
  - hostname: debug.filsha.org
    service: http://localhost:5000
  - hostname: deym.filsha.org
    service: http://localhost:80
  - service: http_status:404